permalink: "/:title"
relative_permalinks: true

highlighter: pygments

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

image_base:          /public/images/

title:               Erik Marty
paginate:            4
baseurl:             ""

sass:
  sass_dir:          _sass
  style:            :compressed

markdown:    redcarpet
excerpt_separator: "<!--break-->"

github: [Repository metadata]
